// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_profile`

/// Decode + score an encoded image (PNG · JPEG · WebP · GIF).
///
/// Returns the `ScanReport` as a JSON string. "No QR found" is a normal result
/// (empty `detections`); `Err` only for invalid input / a bad profile name.
Future<String> scan({required List<int> image, required String profile}) =>
    RustLib.instance.api.crateApiScanScan(image: image, profile: profile);

/// Decode + score a raw RGBA frame (e.g. a camera frame), no format roundtrip.
///
/// `rgba` must be `width * height * 4` bytes.
Future<String> scanFrame(
        {required List<int> rgba,
        required int width,
        required int height,
        required String profile}) =>
    RustLib.instance.api.crateApiScanScanFrame(
        rgba: rgba, width: width, height: height, profile: profile);
